#!/usr/bin/env python
# coding: utf-8

"""
Find the accession with the maximum number of reads per species for re-alignment.

Created on Wed Jun 17 12:04:34 2024

@author: Markus Braun

INTENDED USE
------------
The script identifies the accession with the highest number of mapped reads for each species. 
This selected accession will be used for downstream analysis, including the generation of simplified 
coverage plots, thereby reducing redundancy and optimizing data interpretation.

DESCRIPTION
-----------
The viromics pipeline outputs multiple coverage plots from the `samtools coverage` step. 
To streamline downstream analysis, this script selects the accession with the maximum reads 
per species while applying specific filters to ensure quality:
    - Minimum number of regions covered.
    - Minimum number of covered bases.
    - Minimum region length.
The selected accessions are saved for subsequent re-alignment of reads. This results in a single 
coverage plot per species, aiding clearer data visualization and interpretation.

REQUIREMENTS
------------
This script requires the following:
    1. A tab-separated file with accessions and their mapped read counts (output from `samtools coverage`).
    2. A file mapping accession versions to their taxonomic information, including TaxID and species TaxID 
       (generated from an SQL database via the `make_db` workflow).
    3. A BED file with genome regions covered by reads (output from `bedtools merge`).
    4. Python libraries: `pandas` and `sqlite3`.

INPUT FILES
-----------
1. BED file of merged regions (`bedtools merge` output).
2. Consolidated species identification table after secondary classification.
3. Coverage table generated by `samtools coverage`.
4. SQL database containing taxonomic information.

OUTPUT FILES
------------
1. A text file listing the selected species TaxIDs after applying all filters.
2. A text file listing the selected accessions for downstream alignment and visualization.

PARAMETERS
----------
- `min_number_regions`: Minimum number of non-adjacent genome regions required to be covered.
- `min_covbases`: Minimum number of covered bases required.
- `min_region_length`: Minimum length of aligned genome regions to be counted as a region.

ASSOCIATED FUNCTIONS
--------------------
N/A

FEATURES
--------
1. Filters accessions based on coverage, number of regions, and alignment length.
2. Integrates data from multiple sources (e.g., SQL taxonomy database and BED files).
3. Outputs species and accessions passing all quality filters.
4. Facilitates clearer and reduced coverage plots for easier interpretation.

USAGE
-----
The script is typically executed as part of a Snakemake pipeline, with inputs, parameters, and outputs 
defined in the pipeline configuration. It requires Python 3.x and the required libraries.

DEPENDENCIES
------------
- `pandas`
- `sqlite3`
"""

import sqlite3
import pandas as pd
import os

# path to bedtools merge results on the sorted bam files processed with BamToBed
bedtools_merge_out_path = snakemake.input[0]

# path to species identification table after consolodation using secondary classifier
consolidated_species_list_out_path = snakemake.input[1]

# path to samtools coverage table output
coverage_out_path = snakemake.input[2]

# output path where selected accessions should be saved
accessions_outpath = snakemake.output[0]

# outpath to where the selected species taxids will be saved
species_taxids_outpath = snakemake.output[1]

# outpath to where the files named after each accession will be saved (used in snakemake checkpoint)
accession_files_outpath = snakemake.output[2]

# path to sql taxonomy database
sql_db_path = snakemake.params[0]

# set filters
## set minimum number of genome regions to be covered
min_number_regions = int(snakemake.params[1])

## minumum number of total bases covered in the genome
min_covbases = int(snakemake.params[2])

## Many aligned regions consist just of 1 read => unsufficient support. Filter them out to not make them count when calculating number of covered regions
min_region_length = int(snakemake.params[3])

# basedir = r"/projects/brama/bloodvir/230405_zika/"
# bedtools_merge_out_path = rf"/{basedir}/15_realignment/01_regions/MXB0130_S34_R1R2_sorted_filtered_merged.bed"
# consolidated_species_list_out_path = rf"{basedir}/14_validate_calls/final_classification/MXB0130_S34_R1R2_sorted_filtered_abundances_regions_micop_kaiju.txt"
# coverage_out_path = rf"{basedir}/08_extract_high_coverage_species/MXB0130_S34_R1R2_sorted_filtered.txt"
# accessions_outpath = rf"{basedir}/15_realignment/02_max_reads_accessions/MXB0130_S34_R1R2_sorted_filtered_selected_accessions.txt"
# species_taxids_outpath = rf"{basedir}/15_realignment/02_max_reads_accessions/MXB0130_S34_R1R2_sorted_filtered_selected_species_taxids.txt"
# accession_files_outpath =  rf"{basedir}/15_realignment/02_max_reads_accessions/MXB0130"
# sql_db_path = r"/data/raw/Koenig/241223.bloodvir_MicopRequiredData/NCBI_taxonomy/80perc_contaRemoved_cond_C-RVDBv27_blast_dmpfiles.db"
# min_number_regions = 3
# min_covbases = 1000
# min_region_length = 150

# create output directory if it does not exist
os.makedirs(accession_files_outpath, exist_ok=True)

consolidated_species_list_out_df = pd.read_csv(consolidated_species_list_out_path,
                                        sep="\t", names=["taxid", "species_name", "read_count"])


coverage_out_df = pd.read_csv(coverage_out_path, sep="\t").rename(
    columns={"#rname": "accession_version"}
)
consolidated_species_list_out_df["taxid"] = consolidated_species_list_out_df["taxid"].astype(str)

bed_regions_df = pd.read_csv(bedtools_merge_out_path, sep="\t", names=[
    "accession_version", "start", "end"
])

# Filter out regions with alignments shorter than min_region_length bases in bed regions
bed_regions_df = bed_regions_df[bed_regions_df["end"] - bed_regions_df["start"] >= min_region_length].rename(columns={"start": "no_of_regions"})

# count non-overlapping genome regions covered by reads
bed_regions_count_df = bed_regions_df.groupby("accession_version").agg(
    {"no_of_regions": "count"}
)

# load taxonomy
# load database to map the species taxid to accessions
conn = sqlite3.connect(sql_db_path)
len2taxid_merge_df = pd.read_sql_query("SELECT * from taxon_information_table", conn)
# node2parent_taxid_df = pd.read_sql_query("SELECT * from taxonomy", conn)
conn.close()

# map taxids to accessions
coverage_out_taxids_df = pd.merge(len2taxid_merge_df[[
    "Accession Version_DB", "taxid", "species_taxid"
    ]], coverage_out_df, left_on="Accession Version_DB",
    right_on="accession_version").drop(columns=["Accession Version_DB"])

# add number of regions. This step filters out the accessions with insufficient region/alignment lengths
coverage_out_taxids_regions_df = pd.merge(bed_regions_count_df,coverage_out_taxids_df, on="accession_version")
# find indices of accessions with maximum number of mapped reads
idx = coverage_out_taxids_regions_df.groupby('species_taxid')['numreads'].idxmax()
max_reads_per_species_regions_df = coverage_out_taxids_regions_df.loc[idx]
# filter to only retain accessions present in the consolidated species identification list
max_reads_per_species_regions_2ndclass_filtered_df = max_reads_per_species_regions_df[
    max_reads_per_species_regions_df["species_taxid"].isin(consolidated_species_list_out_df["taxid"])
    ]
# filter using parameters for number of regions covered and number of covered bases
max_reads_per_species_regions_2ndclass_reg_covbases_filtered_df = max_reads_per_species_regions_2ndclass_filtered_df.query(
    "(no_of_regions >= @min_number_regions) | (covbases >= @min_covbases)"
    )
# Since micop output and samtools coverage output indicate different read numbers, accessions with
# #reads<min_number_regions might appear in the identification table. 
# => Remove accessions from df whose read number < min_number_regions in the micop output.
speciesid_smaller_readcount = consolidated_species_list_out_df[
    consolidated_species_list_out_df["read_count"] < min_number_regions
    ]["taxid"]
final_species_list = max_reads_per_species_regions_2ndclass_reg_covbases_filtered_df[
    ~max_reads_per_species_regions_2ndclass_reg_covbases_filtered_df["species_taxid"].isin(speciesid_smaller_readcount)
]


# write list of final species taxids to file after appling ALL 3 filters
species_taxids = final_species_list["species_taxid"].to_list()
with open(species_taxids_outpath, "w") as species_taxids_fout:
    species_taxids_fout.write("\n".join(species_taxids)+"\n")

# The following section will only write the accessions to file that passed 2ndary classification AND coverage filtering
# # Species identified by micop AND kaju will be shown. This helps making decision if a hit is a TP
# accessions = final_species_list["accession_version"].to_list()
# with open(accessions_outpath, "w") as accessions_fout:
#     accessions_fout.write("\n".join(accessions)+"\n")



# Species identified by micop AND kaju will be shown in the coverage plots.Covbase filter, number 
# of adjacent regions filter and alignment length filter are not applied. This helps making decision if a hit is a TP.
# CHANGE HERE TO LATER APPLY THESE FILTERS AND REDUCE THE NUMBER OF COV PLOTS
accessions_2ndclass = max_reads_per_species_regions_2ndclass_filtered_df["accession_version"].to_list()
with open(accessions_outpath, "w") as accessions_fout:
    accessions_fout.write("\n".join(accessions_2ndclass)+"\n")

# Create empty files named after each accession to be used as input for snakemake checkpoint
for accession in accessions_2ndclass:
    # get the species_taxid corresponding to this accession
    matches = coverage_out_taxids_regions_df.query(f"accession_version == '{accession}'")["species_taxid"].values
    if len(matches) == 0:
        print(f"Warning: no match found for {accession}")
        continue
    species_taxid = matches[0]

    # write to file
    with open(f"{accession_files_outpath}/{accession}.txt", "w") as accession_out:
        accession_out.write(f"{species_taxid}\t{accession}\n")
    