#!/usr/bin/env python
# coding: utf-8

"""
Created on Apr 04 2023

@author: brama
"""
"""
INTENDED USE
Map species-level taxids from micop output to their accessions and create a BED file.


DESCRIPTION
This script takes species-level taxids identified by micop and assigns
them  all possible accession numbers that are present in the RVDB
database used for micop. With this and the sequence length information a
BED-file is generated.

REQUIREMENTS
This tool requires the following input files:
    * sql database generated by the make_db  workflow

This script requires "pandas" and sqlite3 to be installed within the Python environment the
script is executed in.

ASSOCIATED FUNCTIONS
This file contains the following functions:
    * create_accession2_length - Return a DataFrame holding accession name and

"""
import sqlite3
import pandas as pd

def load_taxonomy_information(sql_database_path):
    conn = sqlite3.connect(sql_database_path)
    # node2parent_taxid_df = pd.read_sql_query("SELECT * from taxonomy", conn)
    len2taxid_merge_df = pd.read_sql_query("SELECT * from taxon_information_table", conn)
    conn.close()
    return len2taxid_merge_df

path_to_micop_output = snakemake.input[0]
bedfile_outpath = snakemake.output[0]

# load taxids from micop results
with open(path_to_micop_output, "r") as micop_fin:
    taxids = [line.split()[0] for line in micop_fin]

# if input file is empty create empty output file
if not taxids:
    with open(bedfile_outpath, "w") as bed_fout:
        bed_fout.write("")
    exit()

database_path = snakemake.params[0]
len2taxid_merge_df = load_taxonomy_information(database_path)

# map accessions to taxids identified by micop
mapped_accessions = len2taxid_merge_df[len2taxid_merge_df["species_taxid"].isin(taxids)]["Accession Version_DB"].dropna().to_list()

#wirte accessions with regios to bed file 
with open(bedfile_outpath, "w") as bed_fout:
    for accession in mapped_accessions:
        bed_fout.write("\t".join([accession, "0", len2taxid_merge_df.query(f" `Accession Version_DB` == '{accession}'")["Sequence length"].values[0]]) + "\n")
 