# -*- coding: utf-8 -*-
#!/usr/bin/env python3

"""
Script for visualizing the effect of read cutoff values on metagenomic species identification metrics.

Purpose:
--------
Metagenomic classifiers often produce high numbers of false-positive classifications.
This script aims to:
    - Limit false-positive predictions in metagenomic species identification.
    - Determine optimal read cutoff values to balance false positives and true positives.

Functionality:
--------------
The script processes abundance data generated by metagenomic classifiers to calculate
precision, sensitivity, and F1 score and visualizes the metrics to assist in choosing
appropriate cutoff values for filtering criteria.

Requirements:
-------------
Requires `pandas`, `numpy` and `plotly`.

Input:
------
    - Tab-separated file with the number of mapped reads in column 3.
    - Ground truth species data.

Output:
-------
    - Visualization of quality metrics as a plot (HTML/PNG/JPG/PDF).
"""

import csv
import numpy as np
import pandas as pd
import plotly.io as pio
import plotly.graph_objects as go

# Set default renderer for Plotly (for non-Jupyter environments)
pio.renderers.default = "browser"

class QualityMetrics:
    """
    Visualizes precision, sensitivity and F1 score.

    Attributes:
    -----------
    abundance_df : pd.DataFrame
        Dataframe holding abundance data generated by the metagenomics classifier.
    GT_species_number : int
        Number of species present in the ground truth.
    outpath_qm_plot : str
        Output path to save the quality metrics plot.
    GT_species_list : str
        Path to the file containing the ground truth species list.
    """

    def __init__(self, abundance_df, outpath_qm_plot, GT_species_list, outpath_qm_metrics):
        self.abundance_df = abundance_df
        self.outpath_qm_plot = outpath_qm_plot
        self.GT_species_list = GT_species_list
        self.outpath_qm_metrics = outpath_qm_metrics

    def load_ground_truth(self) -> pd.DataFrame:
        """
        Load the ground truth species list into a dataframe.

        Returns:
        --------
        dict:
            Mapping species names to TaxIDs from the ground truth.
        """
        gt_data_df = pd.read_csv(self.GT_species_list, sep="\t", names=["TaxID_GT", "Species_GT", "TaxID_ignore", "Species_ignore"], dtype={"TaxID_GT": str, "TaxID_ignore": str, "Species_GT": str, "Species_ignore": str})

        # get number of species in ground truth
        self.GT_species_number = len(gt_data_df)
        return gt_data_df

    def process_abundance_data(self):
        """
        Process abundance data and calculate true positives (TP) and false positives (FP).

        Returns:
        --------
        pd.DataFrame:
            Processed abundance dataframe with TP and FP annotations.
        """
        # Add "species in ground truth" indicator
        self.spp_in_gt_df = self.load_ground_truth()
        self.abundance_df["spp_in_GT"] = np.where(
            self.abundance_df["blast_species_name"].isin(self.spp_in_gt_df["Species_GT"]), 
            "yes", 
            "no"
        )
        self.abundance_df.loc[
            self.abundance_df["blast_species_name"].isin(self.spp_in_gt_df["Species_ignore"]), 
            "spp_in_GT"
        ] = ""

        # Annotate true positives (TP) and false positives (FP)
        self.abundance_df["TP"] = (self.abundance_df["spp_in_GT"] == "yes").astype(int)
        self.abundance_df["FP"] = (self.abundance_df["spp_in_GT"] == "no").astype(int)
        self.abundance_df.drop_duplicates(subset="blast_species_name", keep='first', inplace=True, ignore_index=False)
        self.abundance_df = self.abundance_df.query("blast_species_name!='-'")
        return self.abundance_df

    def calculate_quality_metrics(self):
        """
        Calculate cumulative quality metrics: precision, sensitivity, F1 score.

        Returns:
        --------
        pd.DataFrame:
            Dataframe with calculated metrics (Precision%, Sensitivity%, F1%).
        """
        self.abundance_df["TP cumsum"] = self.abundance_df["TP"].cumsum()
        self.abundance_df["FP cumsum"] = self.abundance_df["FP"].cumsum()

        self.abundance_df["TP+FP"] = self.abundance_df["TP cumsum"] + self.abundance_df["FP cumsum"]
        self.abundance_df["FP%"] = (self.abundance_df["FP cumsum"] / self.abundance_df["TP+FP"]) * 100
        self.abundance_df["Precision%"] = round((self.abundance_df["TP cumsum"] / self.abundance_df["TP+FP"]) * 100,1)
        self.abundance_df["Sensitivity%"] = round((self.abundance_df["TP cumsum"] / self.GT_species_number) * 100,1)

        # F1 Score calculation (harmonic mean of precision and sensitivity)
        self.abundance_df["F1%"] = (
            2 * self.abundance_df["Precision%"] * self.abundance_df["Sensitivity%"]
        ) / (self.abundance_df["Precision%"] + self.abundance_df["Sensitivity%"])
        self.abundance_df["F1%"] = self.abundance_df["F1%"].round(1)  # Round for better readability
        return self.abundance_df

    def find_max_f1(self):
        """
        Find the row with the maximum F1 score.

        Returns:
        --------
        dict:
            Row containing maximum F1 score and its associated metrics.
        """
        try:
            self.max_f1_row = self.abundance_df.loc[self.abundance_df["F1%"].idxmax()].to_dict()
        except KeyError:
            self.max_f1_row = {"Sensitivity%": 0, "Precision%": 0, "F1%": 0}
            print("no hits found. F1 could not be calculated")
        except ValueError:
            # if self.abundance empty:
            with open(self.outpath_qm_metrics, 'w') as plot_metrics:
                plot_metrics.write("No data available for calculation.")
            fig = go.Figure()
            fig.add_annotation(text="No data", x=0.5, y=0.5, showarrow=False)
            fig.write_image(self.outpath_qm_plot)
            print("no data available to plot")
            sys.exit(0)

        return self.max_f1_row

    def create_precision_sensitivity_plot(self):
        """
        Creates a plot showing Precision, Sensitivity, and F1 Score over cumulative reads.

        This method generates an interactive plot using Plotly that visualizes Precision, 
        Sensitivity, and F1 Score over cumulative reads up to the point where Sensitivity 
        reaches 100%. The plot includes annotations with additional metrics such as the 
        number of covered bases, the number of non-adjacent regions, and the minimum 
        aligned region length.

        Returns:
        --------
        plotly.graph_objects.FigureWidget:
            An interactive Plotly widget displaying the precision, sensitivity, and F1 score plot.
        """
        # Add an index column for x-axis
        self.abundance_df["Index"] = range(len(self.abundance_df))

        # Determine the cutoff index where Sensitivity% reaches 100%
        max_sensitivity = self.abundance_df["Sensitivity%"].iloc[-1]
        cutoff_index = self.abundance_df[self.abundance_df["Sensitivity%"] == max_sensitivity].index[0]

        # Filter the data up to the cutoff point
        filtered_df = self.abundance_df.iloc[:cutoff_index + 1]

        # Create the plot
        fig = go.Figure()

        # Add metrics to the plot
        metrics = [("Precision%", "Precision"), ("Sensitivity%", "Sensitivity"), ("F1%", "F1 Score")]
        for column, name in metrics:
            fig.add_trace(go.Scatter(
                x=filtered_df["Index"],
                y=filtered_df[column],
                mode="lines+markers",
                name=name
            ))

        # Customize the layout
        fig.update_layout(
            title=f"Sample: {snakemake.wildcards.sample}",
            # xaxis_title="Index",
            yaxis_title="Percentage (%)",
            legend_title="Metrics",
            font=dict(size=14),
            hovermode="x unified",  # Combine hover info for all lines at a single x-value
            annotations=[
                dict(
                    x=0.5,  # Position at the center of the plot
                    y=-0.3,  # Position below the x-axis (adjust as needed)
                    text=f"""Precision={self.max_f1_row['Precision%']}
                    Sensitivity={self.max_f1_row['Sensitivity%']}
                    F1={self.max_f1_row['F1%']}
                    <br>number of covered bases = {MIN_COV_BASES}
                    <br>number of non adjacent regions {MIN_NO_REGION} 
                    <br>minimum aligned regions length = {MIN_REGION_LENGTH}""",
                    showarrow=False,
                    font=dict(size=14),
                    align="center",
                    xref="paper",  # Set the x-axis to be paper-relative (global)
                    yref="paper",  # Set the y-axis to be paper-relative (global)
                )
            ],
            margin=dict(t=50, b=150, l=50, r=50),  # Increase bottom margin to create space for annotation
            height=600  # Optionally increase the overall height of the plot
        )


        # Save the plot to a file
        if self.outpath_qm_plot.endswith(".html"):
            fig.write_html(self.outpath_qm_plot)
        else:
            fig.write_image(self.outpath_qm_plot)

        return go.FigureWidget(fig)
    
    def store_quality_metrics(self):
        """
        Stores quality metrics to a file.

        This method appends the current quality metrics, including the minimum number of 
        regions, minimum number of covered bases, minimum region length, and performance 
        metrics (F1, Sensitivity, Precision) to a file at the location specified by 
        `self.outpath_qm_metrics`.

        Returns:
        --------
        None
        """
        with open(self.outpath_qm_metrics, 'a', newline='') as qm_metrics_fout:
            writer = csv.writer(qm_metrics_fout)

            # Write the data in CSV format as a new row
            writer.writerow([
                MIN_NO_REGION, 
                MIN_COV_BASES, 
                MIN_REGION_LENGTH, 
                self.max_f1_row['F1%'], 
                self.max_f1_row['Sensitivity%'], 
                self.max_f1_row['Precision%']
            ])
    


if __name__ == "__main__":
    # INFILE = r"/projects/brama/pipeline_tests/validation/v0.25.3_v4.0.0_ATCC_v100-3M_010subVir_010subMicr_0002subHum/16_revalidation_blast/final_classification/simulated_reads_R1R2_sorted_filtered_selected_accessions_sorted_consensus_blast_final_identification.out"
    # SPECIES_LIST= r"/data/raw/Koenig/241223.bloodvir_MicopRequiredData/ground_truth/ATCC7_ground_truth_and_conta.txt"
    # OUTPATH_PLOT = r"/projects/brama/pipeline_tests/validation/v0.25.3_v4.0.0_ATCC_v100-3M_010subVir_010subMicr_0002subHum/plot.jpg"
    # OUTPATH_QM_METRICS = r"/projects/brama/pipeline_tests/validation/v0.25.3_v4.0.0_ATCC_v100-3M_010subVir_010subMicr_0002subHum/metrics.txt"
    # MIN_NO_REGION = 3
    # MIN_COV_BASES = 1000
    # MIN_REGION_LENGTH = 241
    INFILE = snakemake.input[0]
    SPECIES_LIST= snakemake.params[3]
    OUTPATH_PLOT = snakemake.output[0]
    OUTPATH_QM_METRICS = snakemake.output[1]
    MIN_NO_REGION = snakemake.params[0]
    MIN_COV_BASES = snakemake.params[1]
    MIN_REGION_LENGTH = snakemake.params[2]

    abundance_df = pd.read_csv(INFILE, sep = "\t",
                               usecols=range(8),
                               names=[
                                   "TaxID","Species","# Mapped reads", "Reclassification_passed",
                                   "Filtering_passed", "blast_species_name", "blast_h_name", "Blast_passed"
                                   ],
                               dtype={
                                   "TaxID": str, "Species": str,
                                   "# Mapped reads": int,
                                   "Reclassification_passed": bool,
                                   "Filtering_passed": bool,
                                   "Blast_passed": bool,
                                   "blast_species_name": str,
                                   })
    qm_obj = QualityMetrics(abundance_df, OUTPATH_PLOT, SPECIES_LIST, OUTPATH_QM_METRICS)
    qm_obj.process_abundance_data()
    qm_obj.calculate_quality_metrics()
    qm_obj.find_max_f1()
    plot_widget = qm_obj.create_precision_sensitivity_plot()
    # plot_widget
    qm_obj.store_quality_metrics()

    

