#!/usr/bin/env python
# coding: utf-8

"""
Created on Apr 04 2023

@author: brama
"""
"""
INTENDED USE
Validate micop results by secondary classification using kaiju.


DESCRIPTION
This script takes micop and kaiju results and consolidates them to a single
species identification table

REQUIREMENTS
This tool requires the following input files:
    * sql database generated by the make_db workflow
    * micop results filtered for species
    * consolidated kaiju/micop result table
    * list of identified species taxids after coverage filtering

This script requires "pandas" and sqlite3 to be installed within the Python environment the
script is executed in.

ASSOCIATED FUNCTIONS
This file contains the following functions:
    * load_taxonomy - Return DataFrames holding taxoomy information

"""
import sqlite3
import pandas as pd

def load_taxonomy(sql_database_path):
    conn = sqlite3.connect(sql_database_path)
    taxid2speciestaxid = pd.read_sql_query("SELECT * from taxid2speciestaxid", conn)
    conn.close()
    return taxid2speciestaxid

path_to_micop_output = snakemake.input[0]
path_to_micop_kaiju_output = snakemake.input[1]
selected_species_taxids_path = snakemake.input[2]
database_path = snakemake.params[0]
path_to_identification_table_output = snakemake.output[0]

# load micop-kaiju consolidated table
micop_kaiju_out_df = pd.read_csv(path_to_micop_kaiju_output, sep="\t", dtype={"taxid": str, "species": str, "read_count": int}, names = ["taxid", "species", "read_count"])

# load micop results
micop_output_df = pd.read_csv(path_to_micop_output, sep = "\t", dtype={"taxid": str, "species": str, "read_count": int}, names = ["taxid", "species", "read_count"])

final_identification_table_df = micop_output_df.copy(deep=True)

# load selected species taxids after coverage filter
with open(selected_species_taxids_path, "r") as selected_species_taxids_fin:
        include_taxids = selected_species_taxids_fin.read().split()

# filter for species identified by micop AND kaiju
final_identification_table_df["2nd_classification"] = final_identification_table_df["taxid"].isin(micop_kaiju_out_df["taxid"])

# filter for species that also pass the coverage and non-adjacent regions filter and alignment/region length filter
final_identification_table_df["pass_cov_filter"] = final_identification_table_df["taxid"].isin(include_taxids)
final_identification_table_df.sort_values(["2nd_classification","pass_cov_filter", "read_count"], ascending=False, inplace=True)

# write results to file
final_identification_table_df.to_csv(path_to_identification_table_output, header=False, sep="\t", index=False)
