#!/usr/bin/env python
# coding: utf-8

"""
Created on Apr 04 2023

@author: brama
"""
"""
INTENDED USE
Validate micop results by secondary classification using kaiju.


DESCRIPTION
This script takes micop and kaiju results and consolidates them to a single
species identification table

REQUIREMENTS
This tool requires the following input files:
    * sql database generated by the make_db workflow
    * micop results filtered for species
    * kaiju result table

This script requires "pandas" and sqlite3 to be installed within the Python environment the
script is executed in.

ASSOCIATED FUNCTIONS
This file contains the following functions:
    * load_taxonomy - Return DataFrames holding taxoomy information

"""
import sqlite3
import pandas as pd


path_to_micop_output = snakemake.input[0]
path_to_kaiju_output = snakemake.input[1]
database_path = snakemake.params[0]
path_to_consolidated_output = snakemake.output[0]


def load_taxonomy(sql_database_path):
    conn = sqlite3.connect(sql_database_path)
    taxid2speciestaxid = pd.read_sql_query("SELECT * from taxid2speciestaxid", conn)
    conn.close()
    return taxid2speciestaxid


taxid2speciestaxid_df = load_taxonomy(database_path)

# load kaiju table results
kaiju_out_df = pd.read_csv(path_to_kaiju_output, sep="\t", dtype={"taxon_id": str, "percent": float, "reads": int}).drop("file", axis=1)

# convert to dict for faster processing
taxid_to_species_taxid_dict = taxid2speciestaxid_df.set_index('taxid')['species_taxid'].to_dict()

# add species taxid to to kaiju results
kaiju_out_df["species_taxid"] = kaiju_out_df["taxon_id"].apply(
    lambda x: taxid_to_species_taxid_dict[x] if x in taxid_to_species_taxid_dict else "NA"
)


# load micop results
micop_output_df = pd.read_csv(path_to_micop_output, sep = "\t", dtype={"taxid": str, "species": str, "read_count": int}, names = ["taxid", "species", "read_count"])

# summarize kaiju results on species level
kaiju_species_df = kaiju_out_df.groupby("species_taxid").agg({"percent": "sum", "reads": "sum", "taxon_id": "count", "taxon_name": "first"}).drop("NA",axis='index')

# filter for species identified by micop AND kaiju
micop_kaiju_intersect = micop_output_df[micop_output_df["taxid"].isin(kaiju_species_df.index)]

# write results to file
micop_kaiju_intersect.to_csv(path_to_consolidated_output, header=False, sep="\t", index=False)
