"""Detect Illumina two-color sequencing chemistry from FASTQ headers.

The script examines the first read header of an Illumina FASTQ file and
attempts to identify instruments that use two-color sequencing chemistry.

Both standard Illumina FASTQ headers and SRA-modified headers containing
the original Illumina identifier are supported.

The detection result is written as a JSON file for use by downstream
Snakemake rules.
"""

import gzip
import json


# Instrument prefixes used for Illumina 2-color systems
TWO_COLOR_PREFIXES = {
    "FS": "iSeq 100",
    "MN": "MiniSeq",
    "SH": "MiniSeq",
    "NS": "NextSeq 500/550",
    "NB": "NextSeq 500/550",
    "NDX": "NextSeq 550DX",
    "VL": "NextSeq 1000/2000",
    "VH": "NextSeq 1000/2000",
    "NA": "NovaSeq 6000",
    "A": "NovaSeq 6000",
    "LH": "NovaSeq X",
}


def read_first_header(fastq):
    """Return the first FASTQ header."""
    with gzip.open(fastq, "rt") as fin:
        header = fin.readline().strip()

    if not header.startswith("@"):
        raise ValueError(f"Invalid FASTQ header: {header}")

    return header


def detect_two_color(fastq):
    """
    Detect whether a FASTQ was generated by a known
    Illumina 2-color instrument.

    Supports both original Illumina headers:
        @VH00137:4:AACFGJWM5:...

    and SRA-style headers:
        @SRR30848020.1 VH00137:4:AACFGJWM5:...
    """

    header = read_first_header(fastq)

    # Split the header into whitespace-separated fields.
    # This allows detection in both original and SRA-rewritten headers.
    fields = header.split()

    for field in fields:
        field = field.lstrip("@")

        for prefix, instrument in TWO_COLOR_PREFIXES.items():
            if field.startswith(prefix):
                return {
                    "chemistry": "2-color", 
                    "instrument": instrument, 
                    "instrument_prefix": prefix
                    }

    return {
        "chemistry": "unknown",
        "instrument": "unknown",
        "instrument_prefix": None,
    }


def main():
    fastq = snakemake.input[0]
    output = snakemake.output[0]

    result = detect_two_color(fastq)

    with open(output, "w") as fout:
        json.dump(result, fout, indent=4)



if __name__ == "__main__":
    main()